name: onPush-with-path-limit
 
on:
  push:
    paths:
    - 'sub-project1/**'
    - '!sub-project1/docs/**'  
    - '!sub-project1/README.md'  


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run one-line script
        run: echo a file changed in sub-project1
      - name: Run a multi-line script
        run: |
          echo This is a multi-line script
          echo This is a second line
          echo This is a third line
